apiVersion: v1
kind: Service
metadata:
  name: netology-devcats
spec:
  selector:
    app: devcats
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      nodePort: 30001
  type: NodePort


    