name: Deploy docker image to Kubernetes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to "true" to destroy infrastructure'
        required: false
        default: 'false'
      apply:
        description: 'Set to "true" to apply infrastructure changes'
        required: false
        default: 'false'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devcats:${{ github.sha }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Deploy to Kubernetes
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config
        echo "=== AVAILABLE CONTEXTS ==="
        kubectl config get-contexts --kubeconfig ~/.kube/config
        echo "=== CURRENT CONTEXT ==="
        kubectl config current-context --kubeconfig ~/.kube/config || echo "No current context set"
        echo "=== CLUSTER INFO ==="
        kubectl cluster-info --kubeconfig ~/.kube/config || echo "Cluster info unavailable"
        # Verify the config
        kubectl config view --minify --kubeconfig ~/.kube/config
        kubectl config current-context --kubeconfig ~/.kube/config
        kubectl cluster-info --kubeconfig ~/.kube/config
      env:
        KUBECONFIG: ~/.kube/config

    - name: Verify deployment
      run: kubectl rollout status deployment/devcats-deployment --kubeconfig ~/.kube/config

        
