name: Deploy docker image to Kubernetes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to "true" to destroy infrastructure'
        required: false
        default: 'false'
      apply:
        description: 'Set to "true" to apply infrastructure changes'
        required: false
        default: 'false'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devcats:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Deploy to Kubernetes
      run: |
         kubectl set image deployment/devcats-deployment devcats=atagir/devcats:latest --record
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        
