name: Deploy docker image to Kubernetes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t your-image-name:${{ github.sha }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push Docker image
      run: docker push your-image-name:${{ github.sha }}

    - name: Install kubectl
      uses: kubernetes/setup-kubectl@v1

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/your-deployment your-container=your-image-name:${{ github.sha }} --record
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        
